### ISSUE TITLE
get_group_info群信息获取超时

### ISSUE THREAD

**Issue by hui-ld** [Hoshinonyaruko/Gensokyo#172]
gensokyo端报错：

2023/11/25 18:16:43 Received from onebotv11 server: Action: get_group_info, Params: {"botqq":"","channel_id":"","guild_id":"","group_id":"1","message":null,"user_id":""}, Echo: 3
2023/11/25 18:16:43 handleGetGroupInfo:Error reading config: key 'guild_id' in section '9862xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' does not exist

nonebot2端报错：
【错误报告】
--
创建用户时发生错误
错误类型: <class 'nonebot.adapters.onebot.v11.exception.NetworkError'>
错误值: NetWorkError(message='WebSocket call api get_group_info timeout')
Traceback (most recent call last):
File "/home/bot/nbbot/.venv/lib/python3.9/site-packages/nonebot_plugin_bilibilibot/bili_src/basicFunc.py", line 93, in create_user
group_info = await bot.get_group_info(group_id=user_id)
File "/home/bot/nbbot/.venv/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 123, in call_api
raise exception
File "/home/bot/nbbot/.venv/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
result = await self.adapter._call_api(self, api, **data)
File "/home/bot/nbbot/.venv/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 146, in _call_api
raise NetworkError(f"WebSocket call api {api} timeout") from None
nonebot.adapters.onebot.v11.exception.NetworkError: NetWorkError(message='WebSocket call api get_group_info timeout')

**Comment by Hoshinonyaruko** [comment]
更新最新版gsk
