### ISSUE TITLE
频道私聊转频道的handle_quick_operation会发生crash

### ISSUE THREAD

**Issue by liyk123** [Hoshinonyaruko/Gensokyo#220]
Log如下
```
2023/12/05 18:34:02 Echo:
2023/12/05 18:34:02 Message: version
2023/12/05 18:34:02 MessageSeq: 0
2023/12/05 18:34:02 Font: 0
2023/12/05 18:34:02 UserID: *********
2023/12/05 18:34:02 Received from onebotv11 server: Action: .handle_quick_operation_async, Params: {"botqq":"","channel_id":"","guild_id":"","group_id":"","message":null,"user_id":"","context":{"avatar":"http://thirdqq.qlogo.cn/g?b=oidb\u0026k=IIfbqKDVXOqv8icXEc2lakA\u0026kti=ZUCfTwAAAAI\u0026s=140\u0026t=1555879289","message_id":171785827,"message_type":"group","post_type":"message","sub_type":"normal","time":1701772442,"user_id":*********,"group_id":*********},"operation":{"reply":"Remix-[v4.0.2]"}}, Echo: map[seq:26]
2023/12/05 18:34:02 send_group_msg获取到信息类型:guild_private
panic: interface conversion: interface {} is nil, not string

goroutine 46 [running]:
github.com/hoshinonyaruko/gensokyo/handlers.handleSendGroupMsg({_, _}, {_, _}, {_, _}, {{0x9d527c, 0xe}, {{0x0, 0x0}, ...}, ...})
        /home/runner/work/Gensokyo/Gensokyo/handlers/send_group_msg.go:344 +0x1e54
github.com/hoshinonyaruko/gensokyo/handlers.handle_quick_operation({_, _}, {_, _}, {_, _}, {{0xc0004d7d40, 0x1d}, {{0x0, 0x0}, ...}, ...})
        /home/runner/work/Gensokyo/Gensokyo/handlers/handle_quick_operation.go:22 +0x154
github.com/hoshinonyaruko/gensokyo/callapi.CallAPIFromDict({_, _}, {_, _}, {_, _}, {{0xc0004d7d40, 0x1d}, {{0x0, 0x0}, ...}, ...})
        /home/runner/work/Gensokyo/Gensokyo/callapi/callapi.go:179 +0xe6
github.com/hoshinonyaruko/gensokyo/wsclient.(*WebSocketClient).recvMessage(0xc0003f62a0, {0xc000225e00, 0x1ec, 0x200})
        /home/runner/work/Gensokyo/Gensokyo/wsclient/ws.go:135 +0x22b
created by github.com/hoshinonyaruko/gensokyo/wsclient.(*WebSocketClient).handleIncomingMessages in goroutine 37
        /home/runner/work/Gensokyo/Gensokyo/wsclient/ws.go:71 +0x27
```

**Comment by Hoshinonyaruko** [comment]
不要用频道私信转频道在yobot,这是因为yobot不兼容频道事件,并非gsk问题
